baseURL = "http://mlverse.org/"
languageCode = "en-us"
title = "mlverse.org"
theme = "minimal"

[params]
    showBorder = false
    backgroundColor = "white"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mlverse/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/search?q=%23mlverse"
    name = "twitter"
    weight = 3

